const supabaseUrl="https://evusndlinnzewkommeib.supabase.co";const supabaseKey="sb_publishable_LbcCpdtehJlEBmVlzFWQmg_TFf6AU4L";const supabaseClient=window.supabase.createClient(supabaseUrl,supabaseKey);
let vocabWords=[],words=[],grammarWords=[],jodoushiWords=[],currentMode="vocab",username="",loginId="",score=0,displayedScore=0,combo=0,timeLeft=60,timer=null,currentQuestion=null,answering=false,exploreEndTime=null,exploreInterval=null;
let gameReward=0;
const SHIKIGAMI={fox:{name:"白狐ノ影",image:"img/shikigami_fox_transparent.png",element:"水",role:"語彙特化",rarity:5,base:{hp:1200,atk:240,def:180,spd:90}},tengu:{name:"鴉天狗",image:"img/shikigami_tengu_transparent.png",element:"風",role:"文法特化",rarity:4,base:{hp:1050,atk:260,def:160,spd:120}},dragon:{name:"青龍",image:"img/shikigami_dragon_transparent.png",element:"水",role:"高得点型",rarity:5,base:{hp:1500,atk:300,def:220,spd:80}},kitsune_fire:{name:"九尾ノ焔",image:"img/shikigami_kitsune_fire_transparent.png",element:"火",role:"助動詞特化",rarity:5,base:{hp:1180,atk:340,def:150,spd:100}}};
let activeShikigamiKey=localStorage.getItem("activeShikigamiKey")||"fox";let spiritPower=Number(localStorage.getItem("spiritPower")||0);let coin=Number(localStorage.getItem("coin")||0);let crystal=Number(localStorage.getItem("crystal")||0);let shikigamiState=JSON.parse(localStorage.getItem("shikigamiState")||'{"fox":{"level":1,"exp":0},"tengu":{"level":1,"exp":0},"dragon":{"level":1,"exp":0},"kitsune_fire":{"level":1,"exp":0}}');
const $=id=>document.getElementById(id);const topScreen=$("topScreen"),homeScreen=$("homeScreen"),gameScreen=$("gameScreen"),resultScreen=$("resultScreen"),rankingScreen=$("rankingScreen"),testScreen=$("testScreen"),jodoushiScreen=$("jodoushiScreen"),exploreScreen=$("exploreScreen");const questionEl=$("question"),choicesEl=$("choices"),scoreEl=$("score"),timeEl=$("time"),finalScoreEl=$("finalScore"),rankingList=$("rankingList"),judgeMark=$("judgeMark"),comboText=$("comboText"),comboGauge=$("comboGauge"),scorePlus=$("scorePlus"),goText=$("goText"),menuButton=$("menuButton"),sideMenu=$("sideMenu"),closeMenuButton=$("closeMenu"),overlay=$("overlay"),profileIdInput=$("profileId"),profileNameInput=$("profileName");
window.onload=async function(){let savedLoginId=localStorage.getItem("loginId");const savedName=localStorage.getItem("username");if(!savedLoginId){savedLoginId=generateLoginId();localStorage.setItem("loginId",savedLoginId)}loginId=savedLoginId;if(savedName)username=savedName;await loadWords();await loadGrammar();await loadJodoushi();loadExplore();updateShikigamiUI();};
menuButton.onclick=function(){sideMenu.classList.add("open");overlay.classList.add("show");document.body.classList.add("menu-open")};closeMenuButton.onclick=closeMenu;overlay.onclick=closeMenu;function closeMenu(){sideMenu.classList.remove("open");overlay.classList.remove("show");document.body.classList.remove("menu-open")}
async function loadWords(){try{const res=await fetch("words.csv?v=phase2a");if(!res.ok)throw new Error();vocabWords=parseCSV(await res.text());words=[...vocabWords]}catch(e){console.error(e);alert("words.csvを確認してください")}}
async function loadGrammar(){try{const res=await fetch("grammar.csv?v=phase2a");if(!res.ok)throw new Error();grammarWords=parseCSV(await res.text())}catch(e){console.error(e);alert("grammar.csvを確認してください")}}
async function loadJodoushi(){try{const res=await fetch("jodoushi.csv?v=phase2a");if(!res.ok)throw new Error();jodoushiWords=parseCSV(await res.text())}catch(e){console.error(e);alert("jodoushi.csvを確認してください")}}
function parseCSV(text){const lines=text.trim().split(/\r?\n/),data=[];for(let i=1;i<lines.length;i++){const cols=lines[i].split(",");if(cols.length<2)continue;const q=cols[0].trim(),a=cols[1].trim(),info=cols[2]?cols[2].trim():"";if(q&&a)data.push({question:q,answer:a,info})}return data}
function showScreen(screen){[topScreen,homeScreen,gameScreen,resultScreen,rankingScreen,testScreen,jodoushiScreen,exploreScreen,$("profileScreen")].forEach(s=>s&&s.classList.remove("active"));screen.classList.add("active")}
function setModeTheme(mode){document.body.classList.remove("mode-vocab","mode-grammar","mode-jodoushi");document.body.classList.add("mode-"+mode)}
function goTop(){closeMenu();clearInterval(timer);document.body.classList.remove("no-scroll");showScreen(topScreen)}function goHome(){goTop()}function showVocabHome(){currentMode="vocab";setModeTheme("vocab");words=[...vocabWords];closeMenu();clearInterval(timer);showScreen(homeScreen)}function showGrammarScreen(){closeMenu();clearInterval(timer);showScreen(testScreen)}function showJodoushiScreen(){closeMenu();clearInterval(timer);showScreen(jodoushiScreen)}
function startGrammarGame(){if(!grammarWords.length){alert("文法データが読み込まれていません");return}currentMode="grammar";setModeTheme("grammar");words=[...grammarWords];startGame()}function startJodoushiGame(){if(!jodoushiWords.length){alert("助動詞データが読み込まれていません");return}currentMode="jodoushi";setModeTheme("jodoushi");words=[...jodoushiWords];startGame()}function restartCurrentMode(){if(currentMode==="grammar")startGrammarGame();else if(currentMode==="jodoushi")startJodoushiGame();else{words=[...vocabWords];startGame()}}
function startGame(){document.body.classList.add("no-scroll");loginId=localStorage.getItem("loginId");username=localStorage.getItem("username");if(!loginId||!username){alert("プロフィールを設定してください");openProfile();return}if(!words.length){alert("問題が読み込まれていません");return}score=0;displayedScore=0;combo=0;timeLeft=60;answering=false;scoreEl.textContent=0;timeEl.textContent=60;judgeMark.textContent="";comboText.textContent="";updateComboGauge();closeMenu();showScreen(gameScreen);$("modeTitle").textContent=currentMode==="vocab"?"📘 古典語彙":currentMode==="grammar"?"📖 古典文法":"⚔ 助動詞";showGo();setTimeout(()=>{showQuestion();clearInterval(timer);timer=setInterval(()=>{timeLeft--;timeEl.textContent=timeLeft;if(timeLeft<=0)finishGame()},1000)},800)}
function showQuestion(){answering=false;judgeMark.textContent="";currentQuestion=words[Math.floor(Math.random()*words.length)];questionEl.innerHTML=currentQuestion.info?currentQuestion.question+"<br><span class='question-info'>"+currentQuestion.info+"</span>":currentQuestion.question;const choices=shuffleArray(makeChoices(currentQuestion));choicesEl.innerHTML="";choices.forEach(choice=>{const b=document.createElement("button");b.textContent=choice;b.onclick=()=>checkAnswer(choice);choicesEl.appendChild(b)})}
function makeChoices(q){const correct=q.answer;const wrong=[...new Set(words.map(w=>w.answer).filter(a=>a!==correct))];return [correct,...shuffleArray(wrong).slice(0,3)]}
function checkAnswer(choice){if(answering)return;answering=true;const buttons=choicesEl.querySelectorAll("button");if(choice===currentQuestion.answer){combo++;score+=10+combo;updateComboGauge();if(combo%10===0){timeLeft+=3;timeEl.textContent=timeLeft;showTimeBonus()}showScorePlus(10+combo,combo);buttons.forEach(btn=>{if(btn.textContent===choice)btn.classList.add("correct")});judgeMark.textContent="○";judgeMark.style.color="#ffcc33";showJudge();if(combo>=2){comboText.textContent="COMBO "+combo+"!!";showCombo()}else comboText.textContent=""}else{combo=0;timeLeft=Math.max(0,timeLeft-2);updateComboGauge();buttons.forEach(btn=>{if(btn.textContent===choice)btn.classList.add("wrong");if(btn.textContent===currentQuestion.answer)btn.classList.add("correct")});judgeMark.textContent="×";judgeMark.style.color="#ff4444";comboText.textContent="";showJudge()}animateScore(displayedScore,score);timeEl.textContent=timeLeft;setTimeout(()=>{timeLeft<=0?finishGame():showQuestion()},520)}
function finishGame(){document.body.classList.remove("no-scroll");clearInterval(timer);finalScoreEl.textContent=score;saveRanking(loginId,username,score);gameReward=giveGameReward(score,currentMode);$("rewardText").textContent="獲得霊力 +"+gameReward;showScreen(resultScreen)}
function giveGameReward(score,mode){let rate=mode==="jodoushi"?1.2:mode==="grammar"?1.1:1.0;const reward=Math.floor(score/10*rate);spiritPower+=reward;localStorage.setItem("spiritPower",spiritPower);updateShikigamiUI();return reward}
async function saveRanking(loginId,name,score){const {error}=await supabaseClient.from("scores").insert([{login_id:loginId,name,score,mode:currentMode}]);if(error)console.error("保存エラー:",error)}
async function showRanking(){closeMenu();clearInterval(timer);await showRankingByMode("vocab")}async function showRankingByMode(mode){currentMode=mode;$("rankingTitle").textContent=mode==="vocab"?"古典語彙ランキング":mode==="grammar"?"古典文法ランキング":"助動詞ランキング";const {data,error}=await supabaseClient.from("scores").select("*").eq("mode",mode).order("score",{ascending:false}).limit(200);if(error){console.error("ランキング取得エラー:",error);alert("ランキングを取得できませんでした");return}const best={};(data||[]).forEach(item=>{if(!best[item.login_id]||item.score>best[item.login_id].score)best[item.login_id]=item});const ranking=Object.values(best).sort((a,b)=>b.score-a.score).slice(0,10);rankingList.innerHTML="";if(!ranking.length){const li=document.createElement("li");li.textContent="まだランキングはありません";rankingList.appendChild(li)}else ranking.forEach((item,i)=>{const li=document.createElement("li");li.className=i===0?"rank-1":i===1?"rank-2":i===2?"rank-3":"rank-other";li.textContent=(i+1)+"位　"+item.name+"　"+item.score+"点";rankingList.appendChild(li)});showScreen(rankingScreen)}
function shuffleArray(array){for(let i=array.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[array[i],array[j]]=[array[j],array[i]]}return array}function showJudge(){judgeMark.classList.remove("show");void judgeMark.offsetWidth;judgeMark.classList.add("show")}function showCombo(){comboText.classList.remove("show");void comboText.offsetWidth;comboText.classList.add("show")}function showGo(){goText.classList.remove("show");void goText.offsetWidth;goText.classList.add("show")}function showTimeBonus(){comboText.textContent="3秒追加!!";showCombo()}function showScorePlus(points,comboCount){scorePlus.textContent="+"+points;scorePlus.className="score-plus show"}function animateScore(from,to){const duration=250,start=performance.now();function upd(now){const p=Math.min((now-start)/duration,1);scoreEl.textContent=Math.floor(from+(to-from)*p);if(p<1)requestAnimationFrame(upd);else{displayedScore=to;scoreEl.textContent=to}}requestAnimationFrame(upd)}function updateComboGauge(){comboGauge.style.width=((combo%40)/40*100)+"%"}function generateLoginId(){return"user-"+Math.random().toString(36).substring(2,6)}
function openProfile(){closeMenu();loginId=localStorage.getItem("loginId")||generateLoginId();localStorage.setItem("loginId",loginId);username=localStorage.getItem("username")||"";profileIdInput.value=loginId;profileNameInput.value=username;showScreen($("profileScreen"))}async function saveProfile(){const newName=profileNameInput.value.trim();if(!newName){alert("ユーザーネームを入力してください");return}loginId=localStorage.getItem("loginId");username=newName;localStorage.setItem("username",username);await supabaseClient.from("scores").update({name:username}).eq("login_id",loginId);alert("プロフィールを保存しました")}
function saveShikigami(){localStorage.setItem("spiritPower",spiritPower);localStorage.setItem("coin",coin);localStorage.setItem("crystal",crystal);localStorage.setItem("shikigamiState",JSON.stringify(shikigamiState));localStorage.setItem("activeShikigamiKey",activeShikigamiKey)}function needExp(level){return level*100}function calcStats(key){const d=SHIKIGAMI[key],s=shikigamiState[key]||{level:1,exp:0},lv=s.level;return{hp:d.base.hp+lv*120,atk:d.base.atk+lv*28,def:d.base.def+lv*20,spd:d.base.spd+lv*4,power:d.base.hp+lv*120+(d.base.atk+lv*28)*4+(d.base.def+lv*20)*3+(d.base.spd+lv*4)*2}}
function updateShikigamiUI(){const d=SHIKIGAMI[activeShikigamiKey],s=shikigamiState[activeShikigamiKey]||{level:1,exp:0};if(!d)return;const stats=calcStats(activeShikigamiKey),need=needExp(s.level);setText("activeShikigamiName",d.name);setText("activeRarity","★".repeat(d.rarity)+"☆".repeat(5-d.rarity));const img=$("activeShikigamiImage");if(img)img.src=d.image;setText("activeShikigamiLevel",s.level);setText("battlePowerText",stats.power);setText("elementText",d.element);setText("roleText",d.role);setText("expText",s.exp+" / "+need);const fill=$("expFill");if(fill)fill.style.width=Math.min(100,s.exp/need*100)+"%";setText("hpText",stats.hp);setText("atkText",stats.atk);setText("defText",stats.def);setText("spdText",stats.spd);setText("spiritPowerText",spiritPower);setText("coinText",coin);setText("crystalText",crystal);setText("trainCostText","霊力"+(s.level*100))}function setText(id,v){const el=$(id);if(el)el.textContent=v}
function selectShikigami(key){activeShikigamiKey=key;saveShikigami();updateShikigamiUI()}function trainShikigami(){const s=shikigamiState[activeShikigamiKey]||{level:1,exp:0};const cost=s.level*100;if(spiritPower<cost){alert("霊力が足りません。必要霊力："+cost);return}spiritPower-=cost;s.exp+=80;if(s.exp>=needExp(s.level)){s.exp-=needExp(s.level);s.level++}shikigamiState[activeShikigamiKey]=s;saveShikigami();updateShikigamiUI()}
function showExploreScreen(){closeMenu();clearInterval(timer);showScreen(exploreScreen);updateShikigamiUI();updateExploreUI()}function startExplore(place,hours,type){if(exploreEndTime){alert("すでに探索中です");return}exploreEndTime=Date.now()+hours*60*60*1000;localStorage.setItem("exploreEndTime",exploreEndTime);localStorage.setItem("explorePlace",place);localStorage.setItem("exploreType",type||"water");alert(place+"へ探索に出発しました！");updateExploreUI();clearInterval(exploreInterval);exploreInterval=setInterval(updateExploreUI,1000)}function updateExploreUI(){const panel=$("explorePanel"),timerEl=$("exploreTimer"),placeEl=$("explorePlace");if(!panel||!timerEl)return;if(!exploreEndTime){panel.classList.add("hidden");return}panel.classList.remove("hidden");const place=localStorage.getItem("explorePlace")||"月夜の竹林";if(placeEl)placeEl.textContent=place;const remain=exploreEndTime-Date.now();if(remain<=0){timerEl.textContent="探索完了！";return}const sec=Math.floor(remain/1000),h=String(Math.floor(sec/3600)).padStart(2,"0"),m=String(Math.floor((sec%3600)/60)).padStart(2,"0"),s=String(sec%60).padStart(2,"0");timerEl.textContent=`${h}:${m}:${s}`}function collectExploreReward(){if(!exploreEndTime)return;if(exploreEndTime-Date.now()>0){alert("まだ探索中です");return}const type=localStorage.getItem("exploreType")||"water";const reward=type==="fire"?360:type==="wind"?240:180;spiritPower+=reward;coin+=type==="fire"?150:80;crystal+=type==="wind"?3:1;exploreEndTime=null;localStorage.removeItem("exploreEndTime");localStorage.removeItem("explorePlace");localStorage.removeItem("exploreType");clearInterval(exploreInterval);saveShikigami();updateExploreUI();updateShikigamiUI();alert(`探索成功！\n霊力 +${reward}\n古銭 +${type==="fire"?150:80}\n晶石 +${type==="wind"?3:1}`)}function loadExplore(){const saved=localStorage.getItem("exploreEndTime");if(!saved)return;exploreEndTime=Number(saved);updateExploreUI();clearInterval(exploreInterval);exploreInterval=setInterval(updateExploreUI,1000)}
